name: Docker Image CI

on:
  push:
    branches:
    - master
    #tags:
     # - 'v*.*.*'
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Add release version number to env variable
      run: echo "RELEASE_VERSION=${GITHUB_REF:11}" >> $GITHUB_ENV
    - name: Checkout git repo
      uses: actions/checkout@v2
    - name: Use Node.js (do I need this ?)
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'yarn'
    - name: Install dependencies
      run: yarn
    - name: Run test
      run: yarn test
    - name: Build typescript project
      run: yarn build:ts
    - name: Ls
      run: ls -al
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_REGISTRY_TOKEN }}
    - name: Log in to DigitalOcean Container Registry with short-lived credentials
      run: doctl registry login --expiry-seconds 600
    - name: Build and push Docker images
      uses: docker/build-push-action@v2.6.1
      with:
        push: true
        context: .
        tags: ${{ secrets.DIGITALOCEAN_REGISTRY_URL }}/${{ github.repository }}:${{ env.RELEASE_VERSION }}
