name: Docker Image CI

on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Show version number
      run: echo "Tag version ${GITHUB_REF:11}"
    - name: Checkout git repo
      uses: actions/checkout@v2
    - name: Use Node.js (do I need this ?)
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install dependencies
      run: yarn
    - name: Run test
      run: yarn test
    - name: Build typescript project
      run: yarn build:ts
    - name: Build and push Docker images
      uses: docker/build-push-action@v2.6.1
      with:
        push: false
