name: Docker Image CI

on:
  push:
    branches:
    - master
    #tags:
     # - 'v*.*.*'
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Show version number
      run: echo "Tag version ${GITHUB_REF:11}"
    - name: Checkout git repo
      uses: actions/checkout@v2
    - name: Use Node.js (do I need this ?)
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'yarn'
    - name: Install dependencies
      run: yarn
    - name: Run test
      run: yarn test
    - name: Build typescript project
      run: yarn build:ts
    - name: Ls
      run: ls -al
    - name: Cache dist
      uses: actions/cache@v2.1.6
      with:
        key: /dist
        # A list of files, directories, and wildcard patterns to cache and restore
        path: ./dist
    - name: Build and push Docker images
      uses: docker/build-push-action@v2.6.1
      with:
        push: false
